export const GET_DEVICE_SETTING = 'GET_DEVICE_SETTING';
export const GET_DEVICE_SETTING_SUCCESS = 'GET_DEVICE_SETTING_SUCCESS';
export const GET_DEVICE_SETTING_FAIL = 'GET_DEVICE_SETTING_FAIL';

export const SET_DEVICE_SETTING = 'SET_DEVICE_SETTING';
export const SET_DEVICE_SETTING_SUCCESS = 'SET_DEVICE_SETTING_SUCCESS';
export const SET_DEVICE_SETTING_FAIL = 'SET_DEVICE_SETTING_FAIL';

export const GET_SYSTEM_SETTING = 'GET_SYSTEM_SETTING';
export const GET_SYSTEM_SETTING_SUCCESS = 'GET_SYSTEM_SETTING_SUCCESS';
export const GET_SYSTEM_SETTING_FAIL = 'GET_SYSTEM_SETTING_FAIL';

export const GET_SETTING_OPTIONS = 'GET_SETTING_OPTIONS';
export const GET_SETTING_OPTIONS_SUCCESS = 'GET_SETTING_OPTIONS_SUCCESS';
export const GET_SETTING_OPTIONS_FAIL = 'GET_SETTING_OPTIONS_FAIL';

export const SET_SYSTEM_SETTING = 'SET_SYSTEM_SETTING';
export const SET_SYSTEM_SETTING_SUCCESS = 'SET_SYSTEM_SETTING_SUCCESS';
export const SET_SYSTEM_SETTING_FAIL = 'SET_SYSTEM_SETTING_FAIL';

export const GET_LOCAL_IP = 'GET_LOCAL_IP';
export const GET_LOCAL_IP_SUCCESS = 'GET_LOCAL_IP_SUCCESS';
export const GET_LOCAL_IP_FAIL = 'GET_LOCAL_IP_FAIL';

export const GET_TEMPERATURE = 'GET_TEMPERATURE';
export const GET_TEMPERATURE_SUCCESS = 'GET_TEMPERATURE_SUCCESS';
export const GET_TEMPERATURE_FAIL = 'GET_TEMPERATURE_FAIL';

export const GET_LIST_ROOM = 'GET_LIST_ROOM';
export const GET_LIST_ROOM_SUCCESS = 'GET_LIST_ROOM_SUCCESS';
export const GET_LIST_ROOM_FAIL = 'GET_LIST_ROOM_FAIL';

export const GET_LIST_TABLE = 'GET_LIST_TABLE';
export const GET_LIST_TABLE_SUCCESS = 'GET_LIST_TABLE_SUCCESS';
export const GET_LIST_TABLE_FAIL = 'GET_LIST_TABLE_FAIL';

export const GET_LIST_CPS = 'GET_LIST_CPS';
export const GET_LIST_CPS_SUCCESS = 'GET_LIST_CPS_SUCCESS';
export const GET_LIST_CPS_FAIL = 'GET_LIST_CPS_FAIL';

export const GET_PATIENT_CURRENT_ROOM = 'GET_PATIENT_CURRENT_ROOM';
export const GET_PATIENT_CURRENT_ROOM_SUCCESS =
  'GET_PATIENT_CURRENT_ROOM_SUCCESS';
export const GET_PATIENT_CURRENT_ROOM_FAIL = 'GET_PATIENT_CURRENT_ROOM_FAIL';

export const GET_PATIENT = 'GET_PATIENT';
export const GET_PATIENT_SUCCESS = 'GET_PATIENT_SUCCESS';
export const GET_PATIENT_FAIL = 'GET_PATIENT_FAIL';

export const GET_PRIORITY_PATIENT = 'GET_PRIORITY_PATIENT';
export const GET_PRIORITY_PATIENT_SUCCESS = 'GET_PRIORITY_PATIENT_SUCCESS';
export const GET_PRIORITY_PATIENT_FAIL = 'GET_PRIORITY_PATIENT_FAIL';

export const GET_TNB = 'GET_TNB';
export const GET_TNB_SUCCESS = 'GET_TNB_SUCCESS';
export const GET_TNB_FAIL = 'GET_TNB_FAIL';

export const GET_LIST_PRESENT_PATIENT = 'GET_LIST_PRESENT_PATIENT';
export const GET_LIST_PRESENT_PATIENT_SUCCESS =
  'GET_LIST_PRESENT_PATIENT_SUCCESS';
export const GET_LIST_PRESENT_PATIENT_FAIL = 'GET_LIST_PRESENT_PATIENT_FAILURE';

export const GET_PRESENT_PATIENT = 'GET_PRESENT_PATIENT';
export const GET_PRESENT_PATIENT_SUCCESS = 'GET_PRESENT_PATIENTSUCCESS';
export const GET_PRESENT_PATIENT_FAIL = 'GET_PRESENT_PATIENTFAILURE';

export const GET_RESULT_CLS = 'GET_RESULT_CLS';
export const GET_RESULT_CLS_SUCCESS = 'GET_RESULT_CLS_SUCCESS';
export const GET_RESULT_CLS_FAIL = 'GET_RESULT_CLS_FAILURE';

export const GET_BHYT = 'GET_BHYT';
export const GET_BHYT_SUCCESS = 'GET_BHYT_SUCCESS';
export const GET_BHYT_FAIL = 'GET_BHYT_FAILURE';

export const CHANGE_DEVICE_TYPE = 'CHANGE_DEVICE_TYPE';
export const UPDATE_DEVICE_SETTING_NOT_SAVE = 'UPDATE_DEVICE_SETTING_NOT_SAVE';
export const RESET_STORE = 'RESET_STORE';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAILURE';

export const GET_DEPT_IN_GROUPS = 'GET_DEPT_IN_GROUPS';
export const GET_DEPT_IN_GROUPS_SUCCESS = 'GET_DEPT_IN_GROUPS_SUCCESS';
export const GET_DEPT_IN_GROUPS_FAIL = 'GET_DEPT_IN_GROUPS_FAILURE';

export const GET_ENDO_NAME = 'GET_ENDO_NAME';
export const GET_ENDO_NAME_SUCCESS = 'GET_ENDO_NAME_SUCCESS';
export const GET_ENDO_NAME_FAIL = 'GET_ENDO_NAME_FAILURE';

export const GET_NUMBER_ENDSCOPY = 'GET_NUMBER_ENDSCOPY';
export const GET_NUMBER_ENDSCOPY_SUCCESS = 'GET_NUMBER_ENDSCOPY_SUCCESS';
export const GET_NUMBER_ENDSCOPY_FAIL = 'GET_NUMBER_ENDSCOPY_FAILURE';

export const GET_LAST_PATIENT = 'GET_LAST_PATIENT';
export const GET_LAST_PATIENT_SUCCESS = 'GET_LAST_PATIENT_SUCCESS';
export const GET_LAST_PATIENT_FAIL = 'GET_LAST_PATIENT_FAILURE';
export const GET_LAST_PATIENT_DEPT_VID = 'GET_LAST_PATIENT_DEPT_VID';
export const GET_LAST_PATIENT_DEPT_VID_SUCCESS =
  'GET_LAST_PATIENT_DEPT_VID_SUCCESS';
export const GET_LAST_PATIENT_DEPT_VID_FAIL =
  'GET_LAST_PATIENT_DEPT_VID_FAILURE';
export const CLEAR_LAST_PATIENT_DEPT_VID_FAIL =
  'CLEAR_LAST_PATIENT_DEPT_VID_FAIL';

export const GET_TABLE_BHYT = 'GET_TABLE_BHYT';
export const GET_TABLE_BHYT_SUCCESS = 'GET_TABLE_BHYT_SUCCESS';
export const GET_TABLE_BHYT_FAIL = 'GET_TABLE_BHYT_FAILURE';

export const CLEAR_LIST_ULTRASOUND = 'CLEAR_LIST_ULTRASOUND';
export const CLEAR_LIST_ENDOSCOPY = 'CLEAR_LIST_ENDOSCOPY';
export const SET_TABLE_BHYT = 'SET_TABLE_BHYT';
